### PR TITLE
Update runtime to 5.15-22.08

### LINKED ISSUE #13: Update runtime to 22.08
Would it be possible to update the runtime used by this Flatpak to `5.15-22.08`?

### PR DESCRIPTION
**Pull request by AsciiWolf**
Closes #13.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Tested and seems to work fine.

**Comment by AsciiWolf** [comment]
@christianparpart Feel free to test and merge. Let me know if there is any problem. Thanks! :-)

**Comment by AsciiWolf** [comment]
@hfiguiere Feel free to merge. :-)

**Comment by christianparpart** [comment]
Hey, many thanks and a big big sorry for the absence. There are auch moments in life. I will be reviewing and merging tonight. :-)

**Review by christianparpart — APPROVED** [review]

**Comment by christianparpart** [comment]
Thanks, @AsciiWolf :)

**Pull request merged**
